name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  install:
    runs-on: self-hosted
    container:
      image: public.ecr.aws/docker/library/node:20.18-bookworm
      options: --security-opt label=disable
    steps:
      - uses: actions/checkout@v4
      - name: Save node modules to cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --frozen-lockfile

  lint:
    runs-on: self-hosted
    needs: install
    container:
      image: public.ecr.aws/docker/library/node:20.18-bookworm
      options: --security-opt label=disable
    steps:
      - uses: actions/checkout@v4
      - name: Restore node modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn run lint

  build:
    runs-on: self-hosted
    needs: install
    container:
      image: public.ecr.aws/docker/library/node:20.18-bookworm
      options: --security-opt label=disable
    steps:
      - uses: actions/checkout@v4
      - name: Restore node modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn run build
