name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    DOCKER_HOST: UNIX:///run/user/1001/podman/podman.sock

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

  lint:
    runs-on: self-hosted
    needs: checkout
    container:
      image: public.ecr.aws/docker/library/node:20.18-alpine
    steps:
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: self-hosted
    needs: lint
    container:
      image: public.ecr.aws/docker/library/node:20.18-alpine
    steps:
      - run: yarn run build