name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Debug workspace 1
        run: find . 
        working-directory: ${{ github.workspace }}
      - name: Debug workspace 2
        run: pwd
        working-directory: ${{ github.workspace }}
      - name: Debug CWD
        run: find . 

  lint:
    runs-on: self-hosted
    needs: checkout
    container:
      image: public.ecr.aws/docker/library/node:20.18-alpine
    steps:
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: self-hosted
    needs: lint
    container:
      image: public.ecr.aws/docker/library/node:20.18-alpine
    steps:
      - run: yarn run build