name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Print Environment
        run: printenv
      - name: Debug workspace 1
        run: find . 
        working-directory: ${{ github.workspace }}
      - name: Print current workspace directory
        run: pwd
        working-directory: ${{ github.workspace }}
      - name: Debug CWD
        run: find .
      - name: Find _actions dir
        run: find .
        working-directory: /home/vagrant/actions-runner/_work/_actions

  test123:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Print current working directory
        run: pwd
      - name: Print current workspace directory
        run: pwd
        working-directory: ${{ github.workspace }}
      - name: Find _actions dir
        run: find .
        working-directory: /home/vagrant/actions-runner/_work/_actions

  lint:
    runs-on: self-hosted
    needs: checkout
    container:
      image: public.ecr.aws/docker/library/node:20.18-alpine
    steps:
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  build:
    runs-on: self-hosted
    needs: lint
    container:
      image: public.ecr.aws/docker/library/node:20.18-alpine
    steps:
      - run: yarn run build